### ISSUE TITLE
Add classifier for the AnyIO framework

### ISSUE THREAD

**Issue by agronholm** [pypa/trove-classifiers#11]
Request to add a new Trove classifier.

## The name of the classifier you would like to add

* `Framework :: AnyIO`

## Why do you want to add this classifier?

There are already several projects on PyPI using the "anyio" library. Since PyPI does not have an option to search by dependencies, it would be good to have a trove classifier added so that AnyIO based projects can identify themselves as such for easier searching.

**Comment by thedrow** [comment]
I strongly agree this needs a trove classifier. It's very hard to find clients who support both asyncio and trio anyway, so helping locate them will be beneficial both for Celery and for AnyIO.

**Comment by agronholm** [comment]
You can find most (but not all) supporting libraries and apps here: https://libraries.io/pypi/anyio/dependents. One prominent library missing from this list is httpx because it does not declare a dependency on AnyIO.

**Comment by uSpike** [comment]
Mentioned in #76 but I'll copy here since it's not seeing any activity:
> `anyio` now has 131 dependent packages on PyPI.  `Framework :: AsyncIO` + `Framework :: Trio` results in [12](https://pypi.org/search/?q=anyio&o=&c=Framework+%3A%3A+AsyncIO&c=Framework+%3A%3A+Trio) projects.  It would be very nice to have this new classifier!

**Comment by agronholm** [comment]
Thanks!
