### ISSUE TITLE
Request to add classifier License :: OSI Approved :: Free Public License 1.0.0 (0BSD)

### ISSUE THREAD

**Issue by NIC-MichalLabedzki** [pypa/trove-classifiers#15]
Request to add a new Trove classifiers.

## The name of the classifier you would like to add
* `License :: OSI Approved :: Free Public License 1.0.0 (0BSD)`
* `License :: OSI Approved :: Zero-Clause BSD (0BSD)`

## Why do you want to add this classifiers?
>  Why do the current classifiers not meet your need?

It is new license approved by OSI. See https://opensource.org/licenses/0BSD

> How many projects do you expect to use this new classifier?

This license is also as simple as possible so in future - almost all trivial project or "public domain". For now at least one, my project. (and more my projects in future)

> If you are requesting multiple classifiers, why do you need more than one?

OSI approved this license with two names, but it is only one license. I prefer "Free Public License" as it somehow describes what it is. 0BSD is also good name but there is a need to know BSD license background. There is only one - 0BSD in SPDX, see https://spdx.org/licenses/ , so at least please add "0BSD".

**Comment by hannob** [comment]
Hi, may I ask what the status here is? I was a bit surprised that I'm not allowed to upload a 0BSD-licensed package to pypi.

The blocking issue mentioned in the comment by @jamadden seems to be this https://github.com/pypa/trove-classifiers/issues/17 but tbh I don't see how that's related. It seems there are some existing unclear license classifiers, but why does that prevent new licenses from being added?

**Comment by di** [comment]
If someone wants to make a PR for this, we would merge it.

Note that we generally just want one classifier per SPDX identifier, with the title/identifier aligned with OSI, so this should probably just be:

`License :: OSI Approved :: Zero-Clause BSD (0BSD)`

per https://opensource.org/license/0BSD

**Comment by hannob** [comment]
I just wanted to create a PR, but noted that this has already been done:
https://github.com/pypa/trove-classifiers/commit/cee14ba8dad864274976ae7a131d7efb8ee96752

It also uses exactly the same title/identifier as you proposed - so I guess this issue can be closed?
