### ISSUE TITLE
Add classifier 'Natural Language :: Georgian'

### ISSUE THREAD

**Issue by gmilde** [pypa/trove-classifiers#151]
Support for the Georgian language was added to the Docutils project at commit
https://sourceforge.net/p/docutils/code/9444
Adding "Georgian" to the list of supported languages led to a build failure because the tag is not canonical.

**Comment by di** [comment]
Hi, please feel free to submit a PR which adds this classifier!

**Comment by gmilde** [comment]
I could provide a "diff".

**Comment by NorwayFun** [comment]
Hello,
Could you please tell me what has to be added and where?
Thank you.

**Comment by gmilde** [comment]
Am  9.04.24 schrieb NorwayFun:
> Hello,
> Could you please tell me what has to be added and where?
> Thank you.

The following patch adds the required line to the "canonical classifiers
set":

--- trove_classifiers/__init__.py~	2024-04-10 11:57:15.932544975 +0200
+++ trove_classifiers/__init__.py	2024-04-10 12:41:36.091942609 +0200
@@ -362,6 +362,7 @@
     "Natural Language :: French",
     "Natural Language :: Galician",
     "Natural Language :: German",
+    "Natural Language :: Georgian",
     "Natural Language :: Greek",
     "Natural Language :: Hebrew",
     "Natural Language :: Hindi",

cf. https://github.com/pypa/trove-classifiers/blob/main/CONTRIBUTING.md


We would also appreciate (and use) an entry for the Valencian variant of the
Catalan language:

--- trove_classifiers/__init__.py~	2024-04-10 12:41:36.091942609 +0200
+++ trove_classifiers/__init__.py	2024-04-10 12:49:20.590911164 +0200
@@ -350,6 +350,7 @@
     "Natural Language :: Bulgarian",
     "Natural Language :: Cantonese",
     "Natural Language :: Catalan",
+    "Natural Language :: Catalan (Valencian)",                                 
     "Natural Language :: Chinese (Simplified)",
     "Natural Language :: Chinese (Traditional)",
     "Natural Language :: Croatian",

Should I open a separat issue?

Thank you for looking into this issue.

**Comment by NorwayFun** [comment]
Is OK now, asked a friend to open PR for this. Seems like she did it.

**Comment by gmilde** [comment]
Yes, the PR is here: "Add Natural Language - Georgian #176"  
Thanks!

Could she file one more?

> * The name of the classifier(s) you would like to add:
>
>    Natural Language :: Georgian
>
> * Why do you want to add this classifier?
>
 >   It is required to correctly describe the Docutils project. See https://sourceforge.net/p/docutils/patches/203/

Patch:
~~~ diff
--- trove_classifiers/__init__.py~	2024-04-10 12:41:36.091942609 +0200
+++ trove_classifiers/__init__.py	2024-04-10 12:49:20.590911164 +0200
@@ -350,6 +350,7 @@
     "Natural Language :: Bulgarian",
     "Natural Language :: Cantonese",
     "Natural Language :: Catalan",
+    "Natural Language :: Catalan (Valencian)",
     "Natural Language :: Chinese (Simplified)",
     "Natural Language :: Chinese (Traditional)",
     "Natural Language :: Croatian",
~~~
