### ISSUE TITLE
Missing recent GIT Tags `2023.11.7` and `2023.11.9`?

### ISSUE THREAD

**Issue by hswong3i** [pypa/trove-classifiers#158]
Seems we are missing following GIT tags:

* https://github.com/pypa/trove-classifiers/releases/tag/2023.11.7
* https://github.com/pypa/trove-classifiers/releases/tag/2023.11.9

Which are available from pypi:
* https://pypi.org/project/trove-classifiers/2023.11.7
* https://pypi.org/project/trove-classifiers/2023.11.9

**Comment by di** [comment]
Thanks, look like something about our `release` job is failing: https://github.com/pypa/trove-classifiers/actions/runs/6814646800/job/18531992455.

Will take a look.

**Comment by di** [comment]
I manually added those missing tags but I'm still debugging why the tagging isn't working.

**Comment by di** [comment]
Resolved by #162.
