### ISSUE TITLE
Request trove classifier: Framework :: Celery

### ISSUE THREAD

**Issue by thedrow** [pypa/trove-classifiers#16]
Request to add a new Trove classifier.

## The name of the classifier you would like to add

* `Framework :: Celery`

## Why do you want to add this classifier?
Celery is very widely used in the Python community. Github has many repositories [tagged](https://github.com/topics/celery) with Celery.
It has some projects related to it which are not maintained by the Celery team such as [redbeat](https://github.com/sibson/redbeat) and [flower](https://github.com/mher/flower) among others.

There are some libraries which extend Django's functionality or Flask's functionality using Celery.

Adding a trove classifier would benefit the project as it will make related projects more discoverable.

**Comment by thedrow** [comment]
- [Clearly](https://github.com/rsalmei/clearly)
- [redbeat](https://github.com/sibson/redbeat)
- [flower](https://github.com/mher/flower)
- [celery-progress](https://github.com/czue/celery-progress)
- [django-celery-monitor](https://github.com/jazzband/django-celery-monitor)
- [django-celery-email](https://github.com/pmclanahan/django-celery-email)
- [mixpanel-celery](https://github.com/winhamwr/mixpanel-celery)
- [celery-director](https://github.com/ovh/celery-director)

Regularly receive updates.

It seems that celerybeat-mongo is also infrequently updated.

Is this sufficient?

**Comment by thedrow** [comment]
Also, Airflow uses Celery and so does Dask.
I think we can safely add this trove classifier.

**Comment by thedrow** [comment]
We can add https://github.com/steinitzu/celery-singleton to the list.

**Comment by thedrow** [comment]
https://github.com/ZeitOnline/celery_longterm_scheduler also seems maintained.

@jamadden Can we re-evaluate this?

**Comment by pradyunsg** [comment]
If someone were to file a PR adding the requested classifier (see https://github.com/pypa/trove-classifiers/pull/24), that'd be great! :)

**Comment by thedrow** [comment]
Done!
