### ISSUE TITLE
Why is Ukrainian depricated?

### ISSUE THREAD

**Issue by sizur** [pypa/trove-classifiers#168]
### Why is Ukrainian depricated?

Ukrainian is listed as depricated since the first commit 4 years ago, upto and including now.  What was the reasoning for deplication of Ukrainian?

https://github.com/pypa/trove-classifiers/blame/6e5d25e05fc50ef10cbfcfd234b946028f5e6fec/trove_classifiers/__init__.py#L706

Tagging @di for visibility and insights on this issue.

**Comment by miketheman** [comment]
Probably because in the same commit, the entry was corrected to the new format?
https://github.com/pypa/trove-classifiers/blob/e5c379567a6a5d67c5a2505d6429faca5b69fc45/src/trove_classifiers/__init__.py#L394

**Comment by sizur** [comment]
Ah, a spelling error.

```
In [17]: for classifier in [[c for c in sorted(cs) if c.find("Ukr") != -1] for cs in (classifiers, deprecated_classifiers)]:
    ...:     print(classifier)
    ...:
['Natural Language :: Ukrainian']
['Natural Language :: Ukranian']
```

Not sure if it's worth aligning them in the [README.md](https://github.com/pypa/trove-classifiers/blob/main/README.md), so difference is clear, to help avoid a misunderstanding.  Can just close this.
