### ISSUE TITLE
Request classifier: License :: OSI Approved :: Educational Community License

### ISSUE THREAD

**Issue by tcaduser** [pypa/trove-classifiers#170]
Please add:
License :: OSI Approved :: Educational Community License

It is a variant of the Apache License, with a different patent clause:

https://opensource.org/license/ecl-2-0/

**Comment by miketheman** [comment]
Feel free to submit a pull request that updates https://github.com/pypa/trove-classifiers/blob/main/src/trove_classifiers/__init__.py
