### ISSUE TITLE
Request to change trove for the ooj library.

### ISSUE THREAD

**Issue by KiryxaTech** [pypa/trove-classifiers#185]
I need a new trove identifier because I want to clean up releases from garbage, but I can’t do this because I’ve already used some releases. Can I get a new trove?

Contacts:
- Emails: kiryxatech@gmail.com, kiryxakart@gmail.com
- My PyPI: KiryxaTech
- My lib: ooj
```[tasklist]
### Tasks
```

**Comment by di** [comment]
Hi, I don't understand the request. The classifiers look like this: https://pypi.org/classifiers/, I'm not sure how they relate to using up releases?
