### ISSUE TITLE
ENH: console_script that prints classifiers to stdout

### ISSUE THREAD

**Issue by westurner** [pypa/trove-classifiers#22]
A command that lists the PyPI trove classifiers just like `python setup.py register --list-classifiers` (which doesn't work anymore) in order to list the trove classifiers such that they can be grepped

(This was possible with `setup.py register --list-classifiers`, which doesn't work anymore with a note about twine: https://github.com/pypa/twine/issues/583)

These are the lists:
- https://pypi.org/classifiers/ (HTML)
- https://pypi.org/pypi?%3Aaction=list_classifiers (TXT)
- https://github.com/pypa/trove-classifiers/blob/master/trove_classifiers/__init__.py (Python module containing a list of strs)

Workaround:
```bash
curl -s 'https://pypi.org/pypi?%3Aaction=list_classifiers' \
  | grep -Ei 'development status|license'

```

**Comment by westurner** [comment]
https://github.com/pypa/twine/issues/583 suggests grepping `__init__.py`, which is suboptimal because I don't need quotes for a setup.cfg.

What should the script that just prints each line with or without surrounding quotes be named?

Should it be callable as `python -m trove_classifiers`?

**Comment by di** [comment]
Let's take a step back here: why do you want this? Why do you need to grep a list of classifiers? What are you ultimately trying to achieve?

**Comment by westurner** [comment]
Search for trove classifiers to add to a package; with grep on the commandline.

This was easier to type and remember:
```bash
python setup.py register --list-classifiers
  | grep -Ei 'development status|license'
```

Than this:
```bash
curl -s 'https://pypi.org/pypi?%3Aaction=list_classifiers' \
  | grep -Ei 'development status|license'
```

**Comment by westurner** [comment]
Thanks!
