### ISSUE TITLE
Classifiers identifying supported NVIDIA CUDA version(s)

### ISSUE THREAD

**Issue by angerson** [pypa/trove-classifiers#25]
I'm representing [TensorFlow SIG Build](http://bit.ly/tf-sig-build), a Google-supported community group about building and packaging TensorFlow (a machine learning framework for many different platforms and environments) in OSS. TensorFlow releases each support different versions of [NVIDIA CUDA](https://developer.nvidia.com/cuda-zone), a platform for GPU-accelerated computing, and we think a classifier could be the right place to expose this to users.

Example of what this could look like:

`Environment :: NVIDIA CUDA :: 10.2`
`Environment :: NVIDIA CUDA :: ...`

With one classifier for each of the releases listed on [the NVIDIA CUDA Toolkit archive](https://developer.nvidia.com/cuda-toolkit-archive): 
`10.2, 10.1, 10.0, 9.2, 9.1, 9.0, 8.0, 7.5, 7.0, 6.5, 6.0, 5.5, 5.0, 4.2, 4.1, 4.0, 3.2, 3.1, 3.0, 2.3, 2.2, 2.1, 2.0, 1.1, 1.0`. The list would need to be updated for each CUDA release; judging by that page's release dates, a new release occurs about once or twice per year.

### Notability

TensorFlow and its related projects could make use of CUDA classifiers:

- [TensorFlow](https://www.tensorflow.org): tensorflow, tensorflow-gpu, tf-nightly, tf-nightly-gpu
- TensorFlow Community packages with GPU components: [tensorflow-addons](https://github.com/tensorflow/addons), tfa-nightly

Many existing projects track separate packages to identify the CUDA version and standardizing the information as a classifier would be useful for searching:

- [CuPy](https://github.com/cupy/cupy): cupy-cuda80, cupy-cuda90, cupy-cuda91, cupy-cuda92, cupy-cuda10, cupy-cuda101, cupy-cuda102
- [CuGraph](https://github.com/rapidsai/cugraph): cugraph-cuda92, cugraph-cuda10
- [ThunderSVM](https://github.com/Xtra-Computing/thundersvm): thundersvm-cuda10
- [CuML](https://github.com/rapidsai/cuml): cuml-cuda100, cuml-cuda92
- [CuDF](https://github.com/rapidsai/cudf): cudf-cuda100, cudf-cuda92
- [MxNet](https://mxnet.apache.org/): mxnet-cu92, mxnet-cu92mkl, mxnet-cu91, mxnet-cu91mkl, mxnet-cu90, mxnet-cu90mkl, mxnet-cu80, mxnet-cu80mkl, mxnet-cu75, mxnet-cu75mkl, mxnet-mkl
- [Many others (PyPI)](https://pypi.org/search/?q=cuda)

Other projects simply reference CUDA but don't explicitly state their supported versions, for example:

- [Scikit-CUDA](https://pypi.org/project/scikit-cuda/) 
- [PyTorch](https://pypi.org/project/torch/) (see https://pytorch.org/get-started/locally/)
- [DeepPavlov](https://pypi.org/project/deeppavlov/)

### Considerations / Discussion

- **Classifier Hierarchy:** NVIDIA CUDA is a platform rather than a framework. For this reason I put it under "Environment", but I'm not sure that's the most appropriate, considering...
- **Future patterns:** There are more platforms than just CUDA which TensorFlow and other packages may support in the future, such as MKL (MxNet, above)  and SYCL. I am not an expert on these, but wanted to mention them because Pip cannot group multiples of these platforms under one project name (related: discussion thread for [PEP 599](https://www.python.org/dev/peps/pep-0599/)). Does "Environment" capture all of these kinds of platforms?
- **Referencing NVIDIA CUDA correctly:** I'm not sure if there are more-severe-than-politeness constraints here, as long as we use "NVIDIA CUDA", NVIDIA's preferred reference style.
- **Alternatives:** There is a ["platforms" argument to setuptools.setup()](https://stackoverflow.com/questions/34994130/what-does-the-platforms-argument-to-setup-in-setup-py-do) which seems to be mostly unused. We could use this for extra data like CuDNN version, but nothing here would be standardized.

Ultimately, I think there is a place for a classifier like this, but the specifics may need some more input from the community.

I've previously discussed this a little with @di.

**Comment by di** [comment]
Would something like `Environment :: GPU :: NVIDIA CUDA :: 10.2` make more sense? The current Environment classifiers are a little confusing with the operating systems mixed in, but that would put `Environment :: GPU` along with top-level environment classifiers like:

* `Environment :: Console`
* `Environment :: Web Environment`
* `Environment :: X11 Applications`

which then get more specific.

Besides `NVIDIA CUDA`, what other GPU types might exist here?

**Comment by angerson** [comment]
`Environment :: GPU :: NVIDIA CUDA :: 10.2` makes sense to me. Fitting future sub-classifiers could be e.g. `Environment :: GPU :: Intel MKL :: ...` and this establishes a pattern for the *very* distant future where there could be different `Environment :: TPU :: ...` libraries.

I'm hoping to see some more feedback from the community here, but in the meantime, what is the process / timeline for getting this accepted and merged? Would it be too early to prepare a PR, for instance?

**Comment by jamadden** [comment]
> what is the process / timeline for getting this accepted and merged?

For `Framework` classifiers, we usually ask for ten different maintainers of different active projects to provide input that they will use a proposed classifier before accepting it. That seems like a reasonable standard to apply to `Environment` classifiers as well, IMO.

**Comment by di** [comment]
That requirement is to ensure that we're not adding classifiers for someone's pet project. I don't think the same should apply to things we know exist and are widely used, like GPUs, operating systems, etc.

**Comment by di** [comment]
> Would it be too early to prepare a PR, for instance?

I think it would be fine and would probably also help raise any possible objections.
