### ISSUE TITLE
Request to add `Framework:: Django :: 3.1` classifier.

### ISSUE THREAD

**Issue by felixxm** [pypa/trove-classifiers#29]
Request to add a new trove classifier: `Framework :: Django :: 3.1`

- Why do you want to add this classifier?

Django 3.1 alpha was released on May 14, 2020. See: https://www.djangoproject.com/weblog/2020/may/14/django-31-alpha-1-released/

**Comment by di** [comment]
@felixxm, want to make a PR?

**Comment by felixxm** [comment]
Sure, I can try :+1:

**Comment by felixxm** [comment]
Done, it was straightforward.

**Comment by di** [comment]
This classifier is now available: https://github.com/pypa/warehouse/pull/7991
