### ISSUE TITLE
Automatic deploys 1x a day

### ISSUE THREAD

**Issue by di** [pypa/trove-classifiers#3]
Since this repo is using Github Actions, would be great to add this so there isn't a separate deploy step.

**Comment by pradyunsg** [comment]
What would these deploys need to look like?

**Comment by di** [comment]
@pradyunsg Since this is now CalVer'd, we should bump & release to PyPI 1x a day if there are changes in the last ~24 hours.

**Comment by pradyunsg** [comment]
Hmm... I wonder how we can detect "if there are changes in the last ~24 hours".

**Comment by brainwane** [comment]
Dustin is currently working on this issue [and livestreaming his work](https://www.twitch.tv/di_codes)!
