### ISSUE TITLE
Request "Programming Language :: Kotlin" trove classifier

### ISSUE THREAD

**Issue by ileasile** [pypa/trove-classifiers#41]
Hello! There is a Kotlin programming language, which became quite popular nowadays.

Please add **Programming Language :: Kotlin** classifier!

This is a first package which should get this classifier: https://pypi.org/project/kotlin-jupyter-kernel/

**Comment by di** [comment]
Hi @ileasile, thanks for filing an issue. Makes sense to me, feel free to make a PR against this repository (https://github.com/pypa/trove-classifiers).
