### ISSUE TITLE
Request trove classifier: Framework :: aiohttp

### ISSUE THREAD

**Issue by asvetlov** [pypa/trove-classifiers#54]
Request to add a new Trove classifier.

# The name of the classifier you would like to add

`Framework :: aiohttp`

# Why do you want to add this classifier?

https://github.com/aio-libs/aiohttp is very widely used in the Python community. 
It has 13M downloads per month at the moment of writing: https://pypistats.org/packages/aiohttp
More than 50 libraries officially claim that they are built on top of aiohttp: https://docs.aiohttp.org/en/stable/third_party.html
Many more libraries exist but out of the list.
libraries.io claims that 1141 PyPI packages depend on aiohttp: https://libraries.io/pypi/aiohttp/dependents

Adding a trove classifier would benefit the project as it will make related projects more discoverable. 
aiohttp already has a big and stable ecosystem, adding a dedicated classifier simplifies the searching.

**Comment by webknjaz** [comment]
Hey @di, is there a formal procedure to get a blessing for the new classifier or should someone just go ahead and make a PR? I don't seem to find any instructions on this...

**Comment by di** [comment]
Nope, just make a PR here.

**Comment by asvetlov** [comment]
Done

**Comment by pradyunsg** [comment]
FWIW, there are two requirements we've been using:

- New Framework classifiers should be created if they are "notable" and
- They will be of immediate use to existing projects (in other words, no creating classifiers simply in anticipation of future uses)

aiohttp satisfies both of them, as far as I'm concerned. :)

**Comment by Maillol** [comment]
Hello

I would add the tag to the packages: https://pypi.org/project/aiohttp-pydantic/

**Comment by ri-gilfanov** [comment]
Yes, that's a good idea.

I would add the tag to the package: https://pypi.org/project/aiohttp-sqlalchemy/

**Comment by expert-m** [comment]
I would add the tag to the package: https://pypi.org/project/aiohttp-rpc/
