### ISSUE TITLE
Enforce order for elements in unordered data structures

### ISSUE THREAD

**Issue by di** [pypa/trove-classifiers#7]
In #6 @ewdurbin requested some way to enforce the order of the `classifiers` set and the `deprecated_classifiers` dict in source.

This is not actually a requirement for this library to work correctly, but would be a nice-to-have for maintainers.

**Comment by pradyunsg** [comment]
I mean... we can add a pytest test that reads the file, and checks if the set's contents are indeed correctly. It's OK to be *slightly* fragile at times.

PS: I'm only *slightly* crazy. :)

_Originally posted by @pradyunsg in https://github.com/pypa/trove-classifiers/pull/6#issuecomment-607977087_
