### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by kasium** [pypa/trove-classifiers#95]
Hi,

for the python API, did you consider to add inline type hints or pyi files as well as an `py.typed` file?
If this is added, a programmatic access can be checked by mypy.

I'm happy to open a PR to add this.

**Comment by di** [comment]
Yes, please do!

**Comment by kasium** [comment]
@di what is the minimum python version which is supported by this project. I ask, since the typing module was not in place e.g. in python 3.3.

**Comment by di** [comment]
We haven't had a need to restrict it beyond 'Python 3', but I'd be fine if we made it Python 3.3+ only.

**Comment by kasium** [comment]
Since you have no methods or similar, I just added the py.typed file
