### ISSUE TITLE
Missing git version tags

### ISSUE THREAD

**Issue by kloczek** [pypa/trove-classifiers#99]
According to https://pypi.org/project/trove-classifiers/ last version is 2022.3.30 however there is no in git repo any git version tags.
Is it possible to add at lease `2022.3.30` for last version?

Thx 😄

**Comment by kloczek** [comment]
Thank you very much 😃 🙇

**Comment by kloczek** [comment]
If may Ask to rememve ralways after tagging to to https://github.com/pypa/trove-classifiers/releases and make new release bcause still it is some github issue and add new tag do not sends notyfications to those who have wnabled waching new releases 😄

**Comment by di** [comment]
I'm not sure I understand you, but the releases are automatically generated, so they should always notify.

**Comment by kloczek** [comment]
Hmm so it must be some other github issue because I've not received notyfication.
Or .. email have been stuck on some SMTP relay and I'll receive it soon 😄

**Comment by di** [comment]
FWIW, I got an email notification for the release.
